### ISSUE TITLE
各チームの参考ポイントを作る

### ISSUE THREAD

**Issue by shinsuke79** [yone6379/DiamondGame#14]
現在の状況を参考程度だがポイント化したい
- Board
- UserBoard

それぞれでポイントを作る

**Comment by shinsuke79** [comment]
どうせなら1000ポイントでちょうどゴールになるようにしたい

**Comment by shinsuke79** [comment]
ポイント = 1000 - (各駒のゴールまでの残り距離の合計)
各駒のゴールは一意に定まるわけではないので、何らかのルールを作りたい

**Comment by shinsuke79** [comment]
## 計算の仕様
- ゴールの場所に関わらず、ゴールに辿り着いた駒は距離0とする
- 駒がないゴールはターゲットとなる駒を決める
- ターゲットを決める順序はゴールが深い順とする

## 深い順とは？
- 赤：Xが大きい順(次点でy)
- 黄：Yが大きい順(次点でz)
- 緑：Zが大きい順(次点でx)
  ターゲットは駒の初期位置から離れている順に取得するとする

## 距離の計算について

距離はx.y.zのユークリッド距離とする

## ポイントについて

各駒のゴールまでの進捗率を足したもの

**Comment by shinsuke79** [comment]
UserBoardはBoardの計算結果を使用する

**Comment by yone6379** [comment]
Max100じゃなくてMax1000でもいいかも

**Comment by shinsuke79** [comment]
後は世界のPieceを作成した時に嫌だけど元の場所の座標を覚えさせようと思う

**Comment by shinsuke79** [comment]
やっぱり駒が座標を持つのは変だからBoardに計算機を付けようと思う
ユーザーがボードの状態を変更したときに自動で得点が更新されるイメージで。
駒を配置したときにHashMap<Piece, Cordinate>として初期座標を覚えておく

**Comment by shinsuke79** [comment]
懸念は駒の若い順。駒の番号は適当に割り振られているため、同じ手を打った場合にチームごとに若干差が出てしまう。
本来は深いSpotは浅駒をターゲットにしたほうがいいかも。
結局差は出るが。。。

**Comment by shinsuke79** [comment]
せっかくなので駒も若い順ではなく浅い順にしようと思う
Compare(Team, Spot, Spot)で1が深ければ正の数字を返す関数を作ろうと思う
