### ISSUE TITLE
パフォーマンス改善

### ISSUE THREAD

**Issue by shinsuke79** [yone6379/DiamondGame#25]
ある程度動くようになったのでパフォーマンスにも気を配る

**Comment by yone6379** [comment]
![screenshot-0000](https://cloud.githubusercontent.com/assets/1897253/14056379/70a323c4-f32e-11e5-92a0-51897a6fc1d6.png)

**Comment by shinsuke79** [comment]
![default](https://cloud.githubusercontent.com/assets/1897253/14056429/2bb37222-f32f-11e5-8466-705430a4a739.png)

**Comment by shinsuke79** [comment]
改善結果
![screenshot-0001](https://cloud.githubusercontent.com/assets/1897253/14058091/a87520de-f358-11e5-9bed-547fd7f06a44.png)

**Comment by shinsuke79** [comment]
cloneBoardがまだ遅いけど
他はよさげになった。

**Comment by shinsuke79** [comment]
[DiamondGame.xlsx](https://github.com/yone6379/DiamondGame/files/190357/DiamondGame.xlsx)
