### ISSUE TITLE
幅優先探索Userを作る

### ISSUE THREAD

**Issue by shinsuke79** [yone6379/DiamondGame#27]
#23 のために幅優先探索Userを作成する

**Comment by yone6379** [comment]
Time Size:29 
Max Time:650Msec 
Min Time:131Msec 
Min Time:408Msec

**Comment by shinsuke79** [comment]
探索ターン=2の場合
Time Size:30 
Max Time:724Msec 
Min Time:28Msec 
Min Time:423Msec

**Comment by shinsuke79** [comment]
探索ターン=1の場合
Time Size:35 
Max Time:53Msec 
Min Time:5Msec 
Min Time:16Msec

**Comment by shinsuke79** [comment]
探索ターン=3の場合
途中で破綻したっぽい
Time Size:8 
Max Time:104143Msec 
Min Time:3226Msec 
Min Time:48415Msec

**Comment by shinsuke79** [comment]
無駄すぎる探索は省略する幅優先探索UserNextを作成したところ、
３ターン先まで先読みできるようになった
